import { Link } from '@tanstack/react-router';
import { ArrowRight, BookOpen, CalendarDays, Flower2, Heart, Mail, PenLine, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Brand } from '@/components/journal-shell';
import hero from '@/assets/hero-journal.jpg';
import flowers from '@/assets/memory-flowers.jpg';
import coffee from '@/assets/memory-coffee.jpg';
import seaside from '@/assets/memory-seaside.jpg';

const features = [
  { number: '01', icon: BookOpen, title: 'Personal Chapters', text: 'Put the ordinary and extraordinary into words. Every day is a page worth keeping.', to: '/chapters' as const },
  { number: '02', icon: Flower2, title: 'Mood Garden', text: 'Watch your feelings bloom into a gentle picture of the seasons you’ve lived.', to: '/moods' as const },
  { number: '03', icon: Heart, title: 'Memory Garden', text: 'Gather the photographs, places, and people you never want to forget.', to: '/memories' as const },
  { number: '04', icon: Mail, title: 'Letters to Tomorrow', text: 'Write a little something for the person you are becoming.', to: '/letters' as const },
  { number: '05', icon: CalendarDays, title: 'Monthly Reflection', text: 'Make space to pause, look back, and find the beauty in how far you’ve come.', to: '/reflection' as const },
];
function SectionLabel({ children }: { children: React.ReactNode }) { return <span className="eyebrow">{children}</span>; }
function FinalCTA() { return <section className="final-cta"><div className="container-wide final-cta-inner"><span className="tiny-flower">✽</span><SectionLabel>THIS IS YOUR STORY</SectionLabel><h2>There’s so much beauty<br/>in the <em>in-between.</em></h2><p>Come as you are. Begin wherever you are.</p><Button asChild variant="editorial" size="lg"><Link to="/dashboard">Begin your chapter <ArrowRight size={17}/></Link></Button></div></section>; }
export function HomePage() { return <>
  <section className="home-hero"><img className="hero-image" src={hero} alt="An open journal in warm afternoon light" width={1600} height={1104}/><div className="hero-scrim"/><div className="container-wide hero-content"><span className="hero-eyebrow">A SOFTER PLACE TO LAND  ·  A STORY TO KEEP</span><h1>Your life,<br/>one little chapter<br/><em>at a time.</em></h1><p>A beautiful little space to write your days, hold your memories close, and find the magic in being you.</p><div className="hero-actions"><Button asChild variant="light" size="lg"><Link to="/dashboard">Begin your chapter <ArrowRight size={17}/></Link></Button><Button asChild variant="lightOutline" size="lg"><Link to="/features">Explore features</Link></Button></div></div><div className="hero-bottom">A JOURNAL FOR THE LIFE YOU’RE LIVING <span>↓</span></div></section>
  <section className="intro-section"><div className="container-wide intro-grid"><div><SectionLabel>AN INVITATION TO SLOW DOWN</SectionLabel><h2>The little moments<br/>make a <em>beautiful life.</em></h2></div><div className="intro-copy"><p>Not every day needs to be remarkable to be remembered. Little Chapters is your quiet corner to notice what matters, write what you feel, and keep the moments that feel like home.</p><Link to="/about" className="text-link">Our story <ArrowRight size={16}/></Link></div></div></section>
  <section className="home-feature-section"><div className="container-wide"><div className="section-heading"><div><SectionLabel>YOUR SPACE, YOUR STORY</SectionLabel><h2>Make room for <em>all of it.</em></h2></div><Link to="/features" className="text-link">See all features <ArrowRight size={16}/></Link></div><div className="feature-preview-grid"><Link to="/chapters" className="feature-preview editorial-feature"><div className="feature-preview-text"><span>01 / THE WORDS</span><BookOpen size={29} strokeWidth={1.3}/><h3>Write your chapters</h3><p>A place for your thoughts, your ordinary Tuesdays, and everything in between.</p><span className="circle-arrow"><ArrowRight size={18}/></span></div><div className="editorial-photo"><img src={coffee} alt="Coffee and flowers in a sunlit café" loading="lazy" width={912} height={1104}/></div></Link><Link to="/memories" className="feature-preview memory-feature"><div className="memory-preview-photos"><div className="mini-polaroid left"><img src={flowers} alt="Flowers held on an afternoon walk" loading="lazy" width={912} height={1104}/></div><div className="mini-polaroid right"><img src={seaside} alt="A sunset walk on the beach" loading="lazy" width={912} height={1104}/></div></div><div className="feature-preview-text"><span>02 / THE MOMENTS</span><h3>Keep your memories</h3><p>Little pieces of a life well loved, all in one place.</p><span className="circle-arrow"><ArrowRight size={18}/></span></div></Link><Link to="/moods" className="feature-preview mood-feature"><div className="feature-preview-text"><span>03 / THE FEELINGS</span><Flower2 size={30} strokeWidth={1.3}/><h3>Grow your garden</h3><p>Every feeling has a place to bloom.</p><span className="circle-arrow"><ArrowRight size={18}/></span></div><div className="feature-flower" aria-hidden="true">✿</div></Link></div></div></section>
  <section className="quote-band"><span>✻</span><blockquote>“And all the small things that I thought I’d forget<br/>became the ones I treasure most.”</blockquote><p>A REMINDER TO KEEP THE LITTLE THINGS</p></section>
  <section className="home-about"><div className="container-wide home-about-grid"><div className="about-image-stack"><img src={flowers} alt="A bouquet of flowers on a sunlit walk" loading="lazy" width={912} height={1104}/><span className="photo-caption">some days feel like poetry ♡</span></div><div className="home-about-copy"><SectionLabel>A LITTLE NOTE FROM US</SectionLabel><h2>For the days you<br/>never want to <em>lose.</em></h2><p>We believe your life is made of stories worth telling — the quiet mornings, the unexpected laughter, the moments that changed everything. Little Chapters was made to hold them all with care.</p><Button asChild variant="outline" size="lg"><Link to="/about">More about us <ArrowRight size={17}/></Link></Button></div></div></section>
  <FinalCTA />
</>; }
export function FeaturesPage() { return <><section className="public-page-hero"><div className="container-narrow"><SectionLabel>THE LITTLE THINGS, ALL TOGETHER</SectionLabel><h1>A place for every part<br/>of <em>your story.</em></h1><p>Thoughtfully made for the moments you want to remember, and the feelings you’re still finding words for.</p></div></section><section className="features-list container-wide">{features.map(({ number, icon: Icon, title, text, to }, i) => <Link className="feature-row" to={to} key={number}><span className="feature-number">{number}</span><div className="feature-row-icon"><Icon size={31} strokeWidth={1.35}/></div><div><h2>{title}</h2><p>{text}</p></div><ArrowRight className="feature-row-arrow" size={20}/>{i === 1 && <span className="feature-row-flower" aria-hidden="true">✿</span>}</Link>)}</section><FinalCTA/></>; }
export function AboutPage() { return <><section className="public-page-hero about-hero"><div className="container-narrow"><SectionLabel>WHY LITTLE CHAPTERS</SectionLabel><h1>Because your life<br/>is worth <em>remembering.</em></h1><p>A gentle home for your words, your feelings, and all the little moments that make you, you.</p></div></section><section className="about-story container-wide"><div className="about-story-image"><img src={coffee} alt="A quiet afternoon over coffee" loading="lazy" width={912} height={1104}/><span className="photo-caption">a moment worth keeping</span></div><div className="about-story-copy"><SectionLabel>OUR STORY</SectionLabel><h2>It started with<br/>a simple <em>thought.</em></h2><p>What if we had a place to keep the parts of life that don’t fit into a photo album? The things we felt, the thoughts we nearly forgot, the ordinary days that turned out to mean everything.</p><p>Little Chapters is that place. Not a perfect-life archive, but a living collection of your real one — a quiet space to notice, reflect, and become.</p><p className="script-note">with love, for every version of you ♡</p></div></section><section className="timeline-section"><div className="container-wide"><SectionLabel>YOUR STORY IS STILL UNFOLDING</SectionLabel><h2>There is beauty in <em>becoming.</em></h2><div className="timeline"><div><span>01</span><h3>Notice</h3><p>Find the little things that make an ordinary day yours.</p></div><div><span>02</span><h3>Remember</h3><p>Give your feelings, photos, and words a place to live.</p></div><div><span>03</span><h3>Grow</h3><p>Look back with tenderness at how far you’ve come.</p></div></div></div></section><section className="quote-band"><span>✻</span><blockquote>“You are allowed to be both a masterpiece<br/>and a work in progress.”</blockquote><p>A NOTE FOR WHEREVER YOU ARE TODAY</p></section><FinalCTA/></>; }
